# Pandas
Pandas library in python is used for cleaning, exploring, manipulating & working with the datasets.

#### Two primary data structures used for data manipulation & analysis:
* Series 
* Dataframe

Series is a 1D labelled array that best combines list & dictionary, maintains single collection of orderedvalue, value is assigned with identifier, doesnot have to be unique.

In [1]:
import pandas as pd # import & installation is a prime task before using any libraries

In [2]:
icecream = ['Chocolate', 'Vanilla', 'Strawberry', 'Butterscotch']
print(pd.Series(icecream))

0       Chocolate
1         Vanilla
2      Strawberry
3    Butterscotch
dtype: object

In [3]:
# Create a series object from a dictionary
fish = {       
    'Salmon': 'Orange',  # dictionary key is used as index
    'Tuna': 'Red',
    'Eel': 'Brown'
}
pd.Series(fish)

Salmon    Orange
Tuna         Red
Eel        Brown
dtype: object

In [6]:
# Intro to Series method
prices = pd.Series([2.99, 4.45, 1.36])
prices.sum()

np.float64(8.8)

In [7]:
prices * 3

0     8.97
1    13.35
2     4.08
dtype: float64

In [8]:
prices.product()

np.float64(18.095480000000006)

In [9]:
prices.mean()

np.float64(2.9333333333333336)

In [10]:
prices.std()

np.float64(1.5457791994115246)

In [12]:
# Intro to attribute: Any information related to data
# size: total data in series
# is_unique: duplicated values sequence
adjectives = pd.Series(['Smart', 'Charming', 'Brilliant', 'Humble', 'Smart'])
print(adjectives)

0        Smart
1     Charming
2    Brilliant
3       Humble
4        Smart
dtype: object

In [13]:
adjectives.size

5

In [14]:
adjectives.is_unique

False

In [15]:
adjectives.values

array(['Smart', 'Charming', 'Brilliant', 'Humble', 'Smart'], dtype=object)

In [16]:
adjectives.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
type(adjectives.values)

numpy.ndarray

In [18]:
# Parameters & Arguments
fruits = ['Apple', 'Orange', 'Plum', 'Grapes', 'Watermelon']
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']
pd.Series(fruits, weekdays)

Monday            Apple
Tuesday          Orange
Wednesday          Plum
Thursday         Grapes
Friday       Watermelon
dtype: object

In [ ]:
# CSV: Comma Separated Values
# importing dataset as dataframe
df = pd.read_csv('adult.csv') # df = dataframe

In [ ]:
# Head Method: Shows top 5 elements
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [ ]:
# Tail Method: Shows bottom 5 elements
df.tail()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [ ]:
# Sample: Generates random sample.
df.sample()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
48519,47,Private,294913,Prof-school,15,Married-civ-spouse,Exec-managerial,Husband,White,Male,99999,0,40,United-States,>50K

##### Passing Series to python built-in function

In [26]:
len(df)

48842

In [ ]:
list(df) #converts to series

['age',
 'workclass',
 'fnlwgt',
 'education',
 'educational-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'gender',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country',
 'income']

In [28]:
sorted(df) # sorts in ascending order

['age',
 'capital-gain',
 'capital-loss',
 'education',
 'educational-num',
 'fnlwgt',
 'gender',
 'hours-per-week',
 'income',
 'marital-status',
 'native-country',
 'occupation',
 'race',
 'relationship',
 'workclass']

In [29]:
sorted(df, reverse = True) # sorts in descending order

['workclass',
 'relationship',
 'race',
 'occupation',
 'native-country',
 'marital-status',
 'income',
 'hours-per-week',
 'gender',
 'fnlwgt',
 'educational-num',
 'education',
 'capital-loss',
 'capital-gain',
 'age']

In [30]:
dict(df)

{'age': 0        25
 1        38
 2        28
 3        44
 4        18
          ..
 48837    27
 48838    40
 48839    58
 48840    22
 48841    52
 Name: age, Length: 48842, dtype: int64,
 'workclass': 0             Private
 1             Private
 2           Local-gov
 3             Private
 4                   ?
              ...
 48837         Private
 48838         Private
 48839         Private
 48840         Private
 48841    Self-emp-inc
 Name: workclass, Length: 48842, dtype: object,
 'fnlwgt': 0        226802
 1         89814
 2        336951
 3        160323
 4        103497
           ...
 48837    257302
 48838    154374
 48839    151910
 48840    201490
 48841    287927
 Name: fnlwgt, Length: 48842, dtype: int64,
 'education': 0                11th
 1             HS-grad
 2          Assoc-acdm
 3        Some-college
 4        Some-college
              ...
 48837      Assoc-acdm
 48838         HS-grad
 48839         HS-grad
 48840         HS-grad
 48841         HS-grad
 Name: education, Length: 48842, dtype: object,
 'educational-num': 0         7
 1         9
 2        12
 3        10
 4        10
          ..
 48837    12
 48838     9
 48839     9
 48840     9
 48841     9
 Name: educational-num, Length: 48842, dtype: int64,
 'marital-status': 0             Never-married
 1        Married-civ-spouse
 2        Married-civ-spouse
 3        Married-civ-spouse
 4             Never-married
                 ...
 48837    Married-civ-spouse
 48838    Married-civ-spouse
 48839               Widowed
 48840         Never-married
 48841    Married-civ-spouse
 Name: marital-status, Length: 48842, dtype: object,
 'occupation': 0        Machine-op-inspct
 1          Farming-fishing
 2          Protective-serv
 3        Machine-op-inspct
 4                        ?
                ...
 48837         Tech-support
 48838    Machine-op-inspct
 48839         Adm-clerical
 48840         Adm-clerical
 48841      Exec-managerial
 Name: occupation, Length: 48842, dtype: object,
 'relationship': 0        Own-child
 1          Husband
 2          Husband
 3          Husband
 4        Own-child
            ...
 48837         Wife
 48838      Husband
 48839    Unmarried
 48840    Own-child
 48841         Wife
 Name: relationship, Length: 48842, dtype: object,
 'race': 0        Black
 1        White
 2        White
 3        Black
 4        White
          ...
 48837    White
 48838    White
 48839    White
 48840    White
 48841    White
 Name: race, Length: 48842, dtype: object,
 'gender': 0          Male
 1          Male
 2          Male
 3          Male
 4        Female
           ...
 48837    Female
 48838      Male
 48839    Female
 48840      Male
 48841    Female
 Name: gender, Length: 48842, dtype: object,
 'capital-gain': 0            0
 1            0
 2            0
 3         7688
 4            0
          ...
 48837        0
 48838        0
 48839        0
 48840        0
 48841    15024
 Name: capital-gain, Length: 48842, dtype: int64,
 'capital-loss': 0        0
 1        0
 2        0
 3        0
 4        0
         ..
 48837    0
 48838    0
 48839    0
 48840    0
 48841    0
 Name: capital-loss, Length: 48842, dtype: int64,
 'hours-per-week': 0        40
 1        50
 2        40
 3        40
 4        30
          ..
 48837    38
 48838    40
 48839    40
 48840    20
 48841    40
 Name: hours-per-week, Length: 48842, dtype: int64,
 'native-country': 0        United-States
 1        United-States
 2        United-States
 3        United-States
 4        United-States
              ...
 48837    United-States
 48838    United-States
 48839    United-States
 48840    United-States
 48841    United-States
 Name: native-country, Length: 48842, dtype: object,
 'income': 0        <=50K
 1        <=50K
 2         >50K
 3         >50K
 4        <=50K
          ...
 48837    <=50K
 48838     >50K
 48839    <=50K
 48840    <=50K
 48841     >50K
 Name: income, Length: 48842, dtype: object}

In [31]:
min(df)

'age'

In [32]:
max(df)

'workclass'

#### Dataframe consists of 2D tables with rows and columns

In [33]:
df.values # 2D array as output

array([[25, 'Private', 226802, ..., 40, 'United-States', '<=50K'],
       [38, 'Private', 89814, ..., 50, 'United-States', '<=50K'],
       [28, 'Local-gov', 336951, ..., 40, 'United-States', '>50K'],
       ...,
       [58, 'Private', 151910, ..., 40, 'United-States', '<=50K'],
       [22, 'Private', 201490, ..., 20, 'United-States', '<=50K'],
       [52, 'Self-emp-inc', 287927, ..., 40, 'United-States', '>50K']],
      shape=(48842, 15), dtype=object)

In [35]:
df.shape # number of series & columns

(48842, 15)

In [36]:
df.dtypes #return data types

age                 int64
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [37]:
df.axes

[RangeIndex(start=0, stop=48842, step=1),
 Index(['age', 'workclass', 'fnlwgt', 'education', 'educational-num',
        'marital-status', 'occupation', 'relationship', 'race', 'gender',
        'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
        'income'],
       dtype='object')]

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [39]:
df.sum(numeric_only = True)

age                   1887430
fnlwgt             9263575662
educational-num        492234
capital-gain         52703821
capital-loss          4273788
hours-per-week        1974310
dtype: int64

In [40]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [42]:
# Select multiple columns
df[['age','workclass','marital-status']]

       age     workclass      marital-status
0       25       Private       Never-married
1       38       Private  Married-civ-spouse
2       28     Local-gov  Married-civ-spouse
3       44       Private  Married-civ-spouse
4       18             ?       Never-married
...    ...           ...                 ...
48837   27       Private  Married-civ-spouse
48838   40       Private  Married-civ-spouse
48839   58       Private             Widowed
48840   22       Private       Never-married
48841   52  Self-emp-inc  Married-civ-spouse

[48842 rows x 3 columns]

In [ ]:
# Add new column:
df.insert(loc=1, column = 'name', value = 'anish')

ValueError: cannot insert name, already exists

In [46]:
df

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,anish,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,anish,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,anish,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,anish,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,anish,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,anish,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,anish,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,anish,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [47]:
# multiply
df['capital-gain'].mul(2)

0            0
1            0
2            0
3        15376
4            0
         ...
48837        0
48838        0
48839        0
48840        0
48841    30048
Name: capital-gain, Length: 48842, dtype: int64

In [48]:
# Value Counts
df['age'].value_counts()

age
36    1348
35    1337
33    1335
23    1329
31    1325
      ...
88       6
85       5
87       3
89       2
86       1
Name: count, Length: 74, dtype: int64

In [50]:
# Drop missing values
df.isna().sum()

age                0
name               0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [51]:
df.isnull()

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48838,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48839,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48840,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48841,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [52]:
df.dropna()

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,anish,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,anish,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,anish,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,anish,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,anish,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,anish,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,anish,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,anish,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [57]:
# Fill missing values
df.fillna(0)

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,anish,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,anish,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,anish,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,anish,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,anish,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,anish,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,anish,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,anish,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [58]:
df['workclass'].unique()

array(['Private', 'Local-gov', '?', 'Self-emp-not-inc', 'Federal-gov',
       'State-gov', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [59]:
df['workclass'].nunique()

<bound method IndexOpsMixin.nunique of 0             Private
1             Private
2           Local-gov
3             Private
4                   ?
             ...
48837         Private
48838         Private
48839         Private
48840         Private
48841    Self-emp-inc
Name: workclass, Length: 48842, dtype: object>

In [61]:
df.dtypes

age                 int64
name               object
workclass          object
fnlwgt              int64
education          object
educational-num     int64
marital-status     object
occupation         object
relationship       object
race               object
gender             object
capital-gain        int64
capital-loss        int64
hours-per-week      int64
native-country     object
income             object
dtype: object

In [63]:
# Changing datatype
df['fnlwgt'].astype('float')

0        226802.0
1         89814.0
2        336951.0
3        160323.0
4        103497.0
           ...
48837    257302.0
48838    154374.0
48839    151910.0
48840    201490.0
48841    287927.0
Name: fnlwgt, Length: 48842, dtype: float64

In [64]:
# Sorting
df.sort_values(by = 'age', ascending= True)

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
8257,17,anish,Local-gov,140240,11th,7,Never-married,Adm-clerical,Own-child,White,Female,0,0,20,United-States,<=50K
38,17,anish,Private,269430,10th,6,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,<=50K
12131,17,anish,Private,123947,11th,7,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,15,United-States,<=50K
11999,17,anish,Private,120676,11th,7,Never-married,Sales,Own-child,White,Female,0,0,16,United-States,<=50K
12040,17,anish,Private,188758,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,20,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41584,90,anish,?,175444,7th-8th,4,Separated,?,Not-in-family,White,Female,0,0,15,United-States,<=50K
899,90,anish,Private,149069,Assoc-acdm,12,Married-civ-spouse,Sales,Husband,White,Male,0,1825,50,United-States,>50K
28732,90,anish,?,225063,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Male,0,0,10,South,<=50K
31637,90,anish,Private,90523,HS-grad,9,Widowed,Transport-moving,Unmarried,White,Male,0,0,99,United-States,<=50K
32173,90,anish,Private,88991,Bachelors,13,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,England,>50K

In [65]:
# Rank 
df['age'].rank()

0         9030.0
1        25606.5
2        12652.5
3        32669.0
4         1026.5
          ...
48837    11396.5
48838    28038.0
48839    43987.0
48840     5308.5
48841    40280.5
Name: age, Length: 48842, dtype: float64

In [70]:
# filtering dataframes
# Male working in private class and is never married
is_Male = df['gender'] == 'Male'
pri_work = df['workclass'] == 'private'
is_Married = df['marital-status'] == 'Never-Married'
df[is_Male& pri_work & is_Married]

Empty DataFrame
Columns: [age, name, workclass, fnlwgt, education, educational-num, marital-status, occupation, relationship, race, gender, capital-gain, capital-loss, hours-per-week, native-country, income]
Index: []

In [72]:
#isNull or not null
df[df['gender'].isnull()] 
df[df['gender'].notnull()]

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,anish,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,anish,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,anish,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,anish,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,anish,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,anish,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,anish,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,anish,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [73]:
#Between Method
df[df['age'].between(17,25)]

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
8,24,anish,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
16,20,anish,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,<=50K
23,25,anish,Private,220931,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,Peru,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48793,20,anish,Private,270436,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
48808,22,anish,Private,203715,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
48816,22,anish,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
48836,22,anish,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
48840,22,anish,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [74]:
#duplicated method
df[df['gender'].duplicated(keep = False)]

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,anish,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,anish,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,anish,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,anish,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,anish,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,anish,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,anish,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,anish,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [75]:
#drop duplicates
df.drop_duplicates('gender')

,age,name,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,anish,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
4,18,anish,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K